spring.application.name=smartstock

spring.mongodb.uri=mongodb://admin:123@localhost:27017/smartstockdb?authSource=admin
spring.mongodb.auto-index-creation=true

#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=smartstockdb
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=123
#logging.level.org.mongodb.driver=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG

api.auth-url=http://localhost:3001
api.purchase-sector-url=http://localhost:3001

app.client-id=${APP_CLIENT_ID:ABC}
app.client-secret=${APP_CLIENT_SECRET:DEF}